const data = {
  regions: {
    path: regions,
    name: "regions",
    regionsData: [
      { name: "qoraqalpogiston", value: 48 },
      { name: "xorazm", value: 77 },
      { name: "navoiy", value: 30 },
      { name: "buxoro", value: 11 },
      { name: "qashqadaryo", value: 4 },
      { name: "surxondaryo", value: 66 },
      { name: "samarqand", value: 2 },
      { name: "jizzax", value: 130 },
      { name: "sirdaryo", value: 40 },
      { name: "toshkent", value: 420 },
      { name: "namangan", value: 10 },
      { name: "fargona", value: 0 },
      { name: "andijon", value: 33 },
    ],
  },

  qoraqalpogiston: {
    name: "qoraqalpogiston",
    path: qoraqalpogiston,
    subData: [
      { name: "amudarya", value: 10 },
      { name: "chimbay", value: 30 },
      { name: "kanlikul", value: 12 },
      { name: "shumanay", value: 0 },
      { name: "khojeyli", value: 100 },
      { name: "kegeyli", value: 30 },
      { name: "muynak", value: 0 },
      { name: "nukus", value: 0 },
      { name: "karauzyak", value: 64 },
      { name: "kungrad", value: 100 },
      { name: "takhtakupir", value: 0 },
      { name: "nukus", value: 0 },
      { name: "turtkul", value: 45 },
      { name: "beruniy", value: 0 },
      { name: "urgench", value: 500 },
      { name: "ellikkala", value: 0 },
    ],
  },
  andijon: {
    name: "andijon",
    path: andijon,
    subData: [
      { name: "andijan", value: 0 },
      { name: "ulugnar", value: 0 },
      { name: "khadjaabad", value: 0 },
      { name: "markhamat", value: 0 },
      { name: "asaka", value: 0 },
      { name: "shakhrixan", value: 0 },
      { name: "boz", value: 0 },
      { name: "djalalkuduk", value: 0 },
      { name: "bulakbashi", value: 0 },
      { name: "kurgantepa", value: 0 },
      { name: "balikchi", value: 0 },
      { name: "khanabad", value: 0 },
      { name: "altinkul", value: 0 },
      { name: "andijan", value: 0 },
      { name: "izboskan", value: 0 },
      { name: "paxtaabad", value: 0 },
    ],
  },
  buxoro: {
    name: "buxoro",
    path: buxoro,
    subData: [
      { name: "gijduvan", value: 0 },
      { name: "jondor", value: 0 },
      { name: "alat", value: 0 },
      { name: "kagan", value: 0 },
      { name: "shafirkan", value: 0 },
      { name: "rаmitan", value: 0 },
      { name: "peshku", value: 0 },
      { name: "vabkent", value: 0 },
      { name: "bukhara", value: 0 },
      { name: "bukhara", value: 0 },
      { name: "kagan", value: 0 },
      { name: "karakul", value: 0 },
      { name: "karaulbazar", value: 0 },
    ],
  },
  fargona: {
    name: "fargona",
    path: fargona,
    subData: [
      { name: "kokand", value: 0 },
      { name: "furkat", value: 0 },
      { name: "uzbekistan", value: 0 },
      { name: "besharik", value: 0 },
      { name: "sokh", value: 0 },
      { name: "fergana", value: 0 },
      { name: "kushtepa", value: 0 },
      { name: "buvayda", value: 0 },
      { name: "dangara", value: 0 },
      { name: "yazyavan", value: 0 },
      { name: "kuva", value: 0 },
      { name: "tashlak", value: 0 },
      { name: "margilan", value: 0 },
      { name: "uchkuprik", value: 0 },
      { name: "kuvasay", value: 0 },
      { name: "fergana", value: 0 },
      { name: "altiarik", value: 0 },
      { name: "rishtan", value: 0 },
      { name: "rishtan", value: 0 },
      { name: "bagdad", value: 0 },
    ],
  },
  jizzax: {
    name: "jizzax",
    path: jizzax,
    subData: [
      { name: "farish", value: 0 },
      { name: "mirzachul", value: 0 },
      { name: "arnasay", value: 0 },
      { name: "yangiabad", value: 0 },
      { name: "dzhizak", value: 0 },
      { name: "bakhmal", value: 0 },
      { name: "gallyaaral", value: 0 },
      { name: "dustlik", value: 0 },
      { name: "zafarabad", value: 0 },
      { name: "zaаmin", value: 0 },
      { name: "zarbdar", value: 0 },
      { name: "paxtakor", value: 0 },
      { name: "sharof", value: 0 },
    ],
  },
  namangan: {
    name: "namangan",
    path: namangan,
    subData: [
      { name: "yangikurgan", value: 0 },
      { name: "kasansay", value: 0 },
      { name: "namangan", value: 0 },
      { name: "uychi", value: 0 },
      { name: "chartak", value: 0 },
      { name: "narin", value: 0 },
      { name: "uchkurgan", value: 0 },
      { name: "mingbulak", value: 0 },
      { name: "chust", value: 0 },
      { name: "namangan", value: 0 },
      { name: "pap", value: 0 },
      { name: "turakurgan", value: 0 },
    ],
  },
  navoiy: {
    name: "navoiy",
    path: navoiy,
    subData: [
      { name: "karmana", value: 0 },
      { name: "uchkuduk", value: 0 },
      { name: "kanimekh", value: 0 },
      { name: "tamdi", value: 0 },
      { name: "navbakhor", value: 0 },
      { name: "nurata", value: 0 },
      { name: "navoi", value: 0 },
      { name: "kiziltepa", value: 0 },
      { name: "khatirchi", value: 0 },
      { name: "zarafshan", value: 0 },
    ],
  },
  qashqadaryo: {
    name: "qashqadaryo",
    path: qashqadaryo,
    subData: [
      { name: "yakkabag", value: 0 },
      { name: "kitab", value: 0 },
      { name: "kamashi", value: 0 },
      { name: "karshi", value: 0 },
      { name: "kasbi", value: 0 },
      { name: "mirishkar", value: 0 },
      { name: "nishan", value: 0 },
      { name: "guzar", value: 0 },
      { name: "dehkanabad", value: 0 },
      { name: "kasan", value: 0 },
      { name: "karshi", value: 0 },
      { name: "mubarek", value: 0 },
      { name: "chirakchi", value: 0 },
      { name: "shakhrisabz", value: 0 },
      { name: "shakhrisabz", value: 0 },
    ],
  },
  samarqand: {
    name: "samarqand",
    path: samarqand,
    subData: [
      { name: "bulungur", value: 0 },
      { name: "pakhtachi", value: 0 },
      { name: "pastdargom", value: 0 },
      { name: "ishtikhan", value: 0 },
      { name: "narpay", value: 0 },
      { name: "kattakurgan", value: 0 },
      { name: "kattakurgan", value: 0 },
      { name: "koshrabad", value: 0 },
      { name: "samarkand", value: 0 },
      { name: "urgut", value: 0 },
      { name: "samarkand", value: 0 },
      { name: "taylak", value: 0 },
      { name: "dzhambay", value: 0 },
      { name: "payarik", value: 0 },
      { name: "akdarya", value: 0 },
      { name: "nurabad", value: 0 },
    ],
  },
  sirdaryo: {
    name: "sirdaryo",
    path: sirdaryo,
    subData: [
      { name: "gulistan", value: 0 },
      { name: "saykhunabad", value: 0 },
      { name: "gulistan", value: 0 },
      { name: "akaltin", value: 0 },
      { name: "sirdarya", value: 0 },
      { name: "bayaut", value: 0 },
      { name: "shirin", value: 0 },
      { name: "yangiyer", value: 0 },
      { name: "sardoba", value: 0 },
      { name: "khavas", value: 0 },
      { name: "mirzaabad", value: 0 },
    ],
  },
  surxondaryo: {
    name: "surxondaryo",
    path: surxondaryo,
    subData: [
      { name: "baysun", value: 0 },
      { name: "muzrabad", value: 0 },
      { name: "sherabad", value: 0 },
      { name: "angor", value: 0 },
      { name: "termez", value: 0 },
      { name: "termez", value: 0 },
      { name: "sariasiya", value: 0 },
      { name: "dzharkurgan", value: 0 },
      { name: "kizirik", value: 0 },
      { name: "shurchi", value: 0 },
      { name: "kumkurgan", value: 0 },
      { name: "uzun", value: 0 },
      { name: "altinsay", value: 0 },
      { name: "denau", value: 0 },
    ],
  },
  toshkent: {
    name: "toshkent",
    path: toshkent,
    subData: [
      { name: "bekabad", value: 0 },
      { name: "bekabad", value: 0 },
      { name: "urtachirchik", value: 0 },
      { name: "kuyichirchik", value: 0 },
      { name: "chinaz", value: 0 },
      { name: "akhangaran", value: 0 },
      { name: "buka", value: 0 },
      { name: "akkurgan", value: 0 },
      { name: "pskent", value: 0 },
      { name: "almalik", value: 0 },
      { name: "akhangaran", value: 0 },
      { name: "bektemir", value: 0 },
      { name: "sergeli", value: 0 },
      { name: "yangiyul", value: 0 },
      { name: "yangiyul", value: 0 },
      { name: "chilanzar", value: 0 },
      { name: "uchtepa", value: 0 },
      { name: "tashkent", value: 0 },
      { name: "yakkasaray", value: 0 },
      { name: "almazar", value: 0 },
      { name: "shaykhantokhur", value: 0 },
      { name: "yunusabad", value: 0 },
      { name: "kibray", value: 0 },
      { name: "yashnobod", value: 0 },
      { name: "mirabad", value: 0 },
      { name: "mirzo ulugbek", value: 0 },
      { name: "bostanlik", value: 0 },
      { name: "chirchik", value: 0 },
      { name: "nurafshon", value: 0 },
      { name: "yukarichirchik", value: 0 },
      { name: "parkent", value: 0 },
      { name: "angren", value: 0 },
      { name: "zangiata", value: 0 },
    ],
  },
  xorazm: {
    name: "xorazm",
    path: xorazm,
    subData: [
      { name: "bagat", value: 0 },
      { name: "gurlen", value: 0 },
      { name: "koshkupir", value: 0 },
      { name: "shavat", value: 0 },
      { name: "khiva", value: 0 },
      { name: "khazarasp", value: 0 },
      { name: "khanka", value: 0 },
      { name: "yangiarik", value: 0 },
      { name: "yangibazar", value: 0 },
      { name: "urgench", value: 0 },
      { name: "khiva", value: 0 },
    ],
  },
};
